FROM node:23-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY tsconfig* ./

RUN pnpm install --no-frozen-lockfile

COPY . .

CMD ["pnpm", "run", "start:dev"]