export enum AuthQueues {
    AUTH_MAIL = 'AUTH_MAIL_QUEUE',
}

export enum AuthMailJobs {
    SEND_REGISTER_CODE = 'AUTH_SEND_REGISTER_CODE',
    SEND_RESET_PASSWORD = 'AUTH_SEND_RESET_PASSWORD',
    SEND_CHANGE_EMAIL = 'AUTH_SEND_CHANGE_EMAIL',
}
